### PR TITLE
fix: use .npmignore to avoid publishing dev files

### PR DESCRIPTION
**Pull request by Trott**
Omit .github dir, .travis.yml file, and examples dir in the npm package.

### CODE REVIEW

**Comment by Trott** [comment]
It's pretty obvious given the nature of this change, but just to be sure, I checked that the failure showing in travis is showing for me locally on the master branch and is therefore presumably not because of this change.

**Comment by ihorrusinko** [comment]
Hey @Trott,
Thanks for the fix. Will test what is going on with tests.

**Comment by Trott** [comment]
> Hey @Trott, Thanks for the fix. Will test what is going on with tests.

I'm pretty sure it's just that a more recent botkit/botbuilder adds an extra field in the response JSON.

**Comment by ihorrusinko** [comment]
I expect test kit is working with laster version as well so updated a test. It was change in slack adapter they stopped sending token as part of body.

**Review by ihorrusinko — APPROVED** [review]

**Pull request merged**
